<Project Sdk="Godot.NET.Sdk/4.7.1">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <LangVersion>14.0</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.4.0"/>
        <PackageReference Include="Serilog.Enrichers.CallerInfo" Version="1.0.6"/>
        <PackageReference Include="Serilog.Expressions" Version="5.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
        <PackageReference Include="Serilog.Sinks.GodotConsole" Version="1.2.0"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="TODO.md" />
        <Content Include="Git\Assets\Preview.mp4"/>
        <Content Include="ORIGINALREADME.md" />
        <Content Include="README.md" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Core\Systems\AbilityVisualizer\" />
      <Folder Include="Core\Systems\GameLoopManager\" />
      <Folder Include="Core\Systems\GameManager\" />
    </ItemGroup>
</Project>