#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using AKidsDream.Common.Logging;
using Godot;
using Serilog;
using FileAccess = Godot.FileAccess;

namespace AKidsDream.Common.Generators;

public class StaticFieldClassGenerator
{
    private static readonly ILogger Log = GameLogger.For<StaticFieldClassGenerator>();

    public static void Generate(
        string outputDir,
        string className,
        IEnumerable<(string FieldName, object Value)> entries,
        Func<object, string> valueLiteral,
        IEnumerable<string> usings,
        string? namespaceName = null)
    {
        var fileName = $"{className}.g.cs";
        var outputPath = Path.Combine(outputDir, fileName);

        // -- CHECKS --
        Error directoryError = DirAccess.MakeDirRecursiveAbsolute(outputDir);
        if (directoryError != Error.Ok)
        {
            Log.Here().Err($"Failed to create directory at {outputDir}: {directoryError}");
            return;
        }

        if (className.ToPascalCase() != className)
            Log.Here().Warn($"Class name {className} is not in PascalCase");

        // -- GENERATION --
        namespaceName ??= GetNamespaceFromOutputDir(outputDir);

        var sb = GenerateClass(className, entries, valueLiteral, namespaceName, usings);

        // -- WRITE --
        using var file = FileAccess.Open(outputPath, FileAccess.ModeFlags.Write);
        if (file is null)
            throw new Exception($"Failed to open file at {outputPath}");

        file.StoreString(sb.ToString());
    }

    private static string? GetNamespaceFromOutputDir(
        string outputDir
    )
    {
        string absRootPath = ProjectSettings.GlobalizePath("res://");
        var rootNamespace = Path.GetFileName(absRootPath.TrimEnd('/', '\\'));
        if (string.IsNullOrEmpty(rootNamespace))
        {
            Log.Here().Err("Failed to get root namespace");
            return null;
        }

        var pathFromRootNamespace = outputDir;
        if (!outputDir.StartsWith("res://"))
        {
            var indexOfRoot = outputDir.IndexOf(rootNamespace, StringComparison.Ordinal);
            if (indexOfRoot >= 0)
                pathFromRootNamespace = outputDir.Substring(indexOfRoot);
        }

        string relativePath = pathFromRootNamespace
            .Replace("//", "/")
            .Replace("\\", "/")
            .TrimEnd('/')
            .Replace("res://", "", StringComparison.OrdinalIgnoreCase);

        if (relativePath.Length == 0)
            return rootNamespace;

        string[] segments = relativePath
            .Split('/', StringSplitOptions.RemoveEmptyEntries)
            .Select(ToPascalCaseIdentifier)
            .ToArray();

        return $"{rootNamespace}.{segments.Join(".")}";
    }

    private static string ToPascalCaseIdentifier(string segment)
    {
        var sb = new StringBuilder();
        bool capitalizeNext = true;

        foreach (char c in segment)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
            {
                // Identifiers cannot start with a digit.
                if (sb.Length == 0 && char.IsDigit(c))
                    sb.Append('_');

                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
            else
            {
                // Hyphens, spaces, etc. become word separators.
                capitalizeNext = true;
            }
        }

        return sb.Length > 0 ? sb.ToString() : "Generated";
    }

    private static StringBuilder GenerateClass(
        string className,
        IEnumerable<(string FieldName, object Value)> entries,
        Func<object, string> valueLiteral,
        string? namespaceName,
        IEnumerable<string> usings
    )
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> Do not edit by hand. </auto-generated>");
        foreach (var usingDirective in usings)
        {
            sb.AppendLine($"using {usingDirective};");
        }

        sb.AppendLine();
        if (!string.IsNullOrEmpty(namespaceName))
            sb.AppendLine($"namespace {namespaceName};");

        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        var failedFields = new List<(string FieldName, Exception Exception)>();
        foreach (var (fieldName, value) in entries)
        {
            try
            {
                var literal = valueLiteral(value);
                sb.AppendLine($"    public static readonly {value.GetType().Name} {fieldName} = {literal};");
            }
            catch (Exception e)
            {
                failedFields.Add((fieldName, e));
            }
        }

        if (failedFields.Count > 0)
            OS.Alert(
                "Failed to generate Field for: \n" +
                string.Join("\n",
                    failedFields.Select(f => $"Field: '{f.FieldName}' -> {f.Exception.Message}")
                )
            );

        sb.AppendLine("}");

        return sb;
    }
}